apiVersion: apps/v1
kind: Deployment
metadata:
  name: myresume
spec:
  selector:
    matchLabels:
      app: myresume
  replicas: 2
  template:
    metadata:
      labels:
        app: myresume
    spec:
      containers:
      - name: myresume
        image: mohamedaql/myresume:1.0
        ports:
        - containerPort: 8090
