apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqlphpmyadmin
spec:
  selector:
    matchLabels:
      app: aqlphpmyadmin
  replicas: 2
  template:
    metadata:
      labels:
        app: aqlphpmyadmin
    spec:
      containers:
      - name: aqlphpmyadmin
        image: mohamedaql/aqlphpmyadmin:1.0
        ports:
        - containerPort: 8090
