apiVersion: apps/v1
kind: Deployment
metadata:
  name: testdocker1
spec:
  selector:
    matchLabels:
      app: testdocker1
  replicas: 1
  template:
    metadata:
      labels:
        app: testdocker1
    spec:
      containers:
      - name: testdocker1
        image: mohamedaql/testdocker1:latest
        ports:
        - containerPort: 8090
