apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainrepo
spec:
  selector:
    matchLabels:
      app: mainrepo
  replicas: 1
  template:
    metadata:
      labels:
        app: mainrepo
    spec:
      containers:
      - name: mainrepo
        image: docker.io/mohamedaql/mainrepo:1.3
        ports:
        - containerPort: 8090
         
      imagePullSecrets: 
        - name: regcred-dockerhub
        
