apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqlphpmyadmin
spec:
  selector:
    matchLabels:
      app: aqlphpmyadmin
  replicas: 2
  template:
    metadata:
      labels:
        app: aqlphpmyadmin
    spec:
      containers:
      - name: aqlphpmyadmin
        image: mohamedaql/aqlphpmyadmin:1.2
        ports:
        - containerPort: 8090
         env: 
            - name: DOCKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dockerhub-credentials 
                  key: DOCKER_USERNAME
            - name: DOCKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dockerhub-credentials 
                  key: DOCKER_PASSWORD
      imagePullSecrets: 
        - name: regcred-dockerhub
        
