apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqlphpmyadmin
spec:
  selector:
    matchLabels:
      app: aqlphpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: aqlphpmyadmin
    spec:
      containers:
      - name: aqlphpmyadmin
        image: registry-1.docker.io/mohamedaql/aqlphpmyadmin:1.0
        ports:
        - containerPort: 8090
         
      imagePullSecrets: 
        - name: regcred-dockerhub
        
