apiVersion: apps/v1
kind: Deployment
metadata:
  name: myresume
spec:
  selector:
    matchLabels:
      app: myresume
  replicas: 1
  template:
    metadata:
      labels:
        app: myresume
    spec:
      containers:
      - name: myresume
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8090
