apiVersion: apps/v1
kind: Deployment
metadata:
  name: myresume
spec:
  selector:
    matchLabels:
      app: myresume
  replicas: 
  template:
    metadata:
      labels:
        app: myresume
    spec:
      containers:
      - name: myresume
        image: myresume:1.0 # Use a specific version here
        ports:
        - containerPort: 8090
