apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
patches:
  - target:
      kind: Deployment
      name: app
    path: patch-imagepullsecrets.yaml
images:
  - name: docker.io/mohamedaql/mainrepo
